# ===============================================================
# NexT Theme Configuration
# ===============================================================

# ---------------------------------------------------------------
# Scheme Settings - 樣式設定
# ---------------------------------------------------------------

# 切換到 Pisces 樣式
scheme: Pisces

# 啟用亮色模式
darkmode: false

# ---------------------------------------------------------------
# Site Information Settings - 網站資訊設定
# ---------------------------------------------------------------

# 網站圖示設定
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png

# 頭像設定
avatar:
  # 頭像圖片路徑
  url: /images/avatar.gif
  # 是否為圓形
  rounded: true
  # 滑鼠懸停時旋轉
  rotated: true

# ---------------------------------------------------------------
# Menu Settings - 選單設定
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# 啟用 / 停用選單圖示
menu_settings:
  icons: true
  badges: false

# ---------------------------------------------------------------
# Sidebar Settings - 側邊欄設定
# ---------------------------------------------------------------

sidebar:
  # 側邊欄位置
  position: left
  # 側邊欄顯示時機 (post | always | hide | remove)
  display: always
  # 側邊欄填充
  padding: 18
  # 側邊欄偏移
  offset: 12

# ---------------------------------------------------------------
# Footer Settings - 頁尾設定
# ---------------------------------------------------------------

footer:
  # 指定網站建立時間
  since: 2025
  # 圖示和網站之間的圖示
  icon:
    # 圖示名稱
    name: fa fa-heart
    # 圖示動畫
    animated: true
    # 圖示顏色
    color: "#ff0000"
  # 版權資訊
  copyright:
  # 由...驅動資訊
  powered: true
  # 主題與版本
  theme:
    enable: true
    version: true

# ---------------------------------------------------------------
# Post Settings - 文章設定
# ---------------------------------------------------------------

# 自動摘錄描述
excerpt_description: true

# 閱讀更多按鈕
read_more_btn: true

# 文章 meta 顯示
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true

# Post edit
# Easily browse and edit blog source code online.
post_edit:
  enable: false

# 目錄設定 (Table of Contents)
toc:
  enable: true
  number: true
  wrap: true
  expand_all: false
  max_depth: 6

# ---------------------------------------------------------------
# Custom Style Settings - 自定義樣式設定
# ---------------------------------------------------------------

# 自定義樣式
custom_file_path:
  # 如果需要自定義變數，可以取消註解
  #variable: source/_data/variables.styl
  # 如果需要自定義樣式，可以取消註解
  #style: source/_data/styles.styl

# ---------------------------------------------------------------
# Optimization - 效能優化
# ---------------------------------------------------------------

# 壓縮 HTML
minify: false

# 緩存設定
cache:
  enable: true

# ---------------------------------------------------------------
# SEO & Analytics - SEO和分析設定
# ---------------------------------------------------------------

# Google Analytics 4 (gtag.js)
# 請先到 https://analytics.google.com/ 創建帳戶並獲取追蹤ID
google_analytics:
  tracking_id: G-ZSYREEJDQE
  only_pageview: false

# 或者使用gtag配置
gtag:
  enable: true
  tracking_id: G-ZSYREEJDQE
  anonymize_ip: false

# Bing站長工具驗證（可選）
bing_site_verification: # 如果需要，請填入Bing驗證碼

# ---------------------------------------------------------------
# Google AdSense 設定
# ---------------------------------------------------------------

# Google AdSense
# 申請通過後，將 AdSense 發布商ID填入下方
google_adsense:
  enable: false  # 申請通過後改為 true
  client_id: # 格式：ca-pub-xxxxxxxxxxxxxxxx
  auto_ads: true  # 啟用自動廣告

# ---------------------------------------------------------------
# 聯盟行銷設定
# ---------------------------------------------------------------

# 聯盟行銷連結追蹤
affiliate_marketing:
  enable: true
  disclosure_text: "本文包含聯盟連結，如果您通過這些連結購買，我可能會獲得小額佣金，但不會增加您的成本。"
  
  # 台灣平台
  taiwan_platforms:
    books_com_tw: # 博客來聯盟ID
    pchome: # PChome聯盟ID
    shopee: # 蝦皮聯盟ID
    
  # 國際平台
  international_platforms:
    udemy: # Udemy聯盟ID
    coursera: # Coursera聯盟ID
    hostinger: # Hostinger聯盟ID
    digitalocean: # DigitalOcean聯盟ID
